name: cards
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  reflectable: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - models/cars.json
    - models/shop.json
    - models/utenti.json